<?php

namespace Database\Seeders;

use App\Models\CourseCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CourseCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CourseCategory::insert([
            [
                'image' => 'uploads/seeder_image/categories_image/media_69495a4c77aa5.png',
                'name' => 'Web Development',
                'slug' => Str::slug('Web Development'),
                'parent_id' => null,
                'show_at_trending' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/categories_image/media_69495ac8c3b2d.png',
                'name' => 'Programming Language',
                'slug' => Str::slug('Programming Language'),
                'parent_id' => null,
                'show_at_trending' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/categories_image/media_69495b3a38b0d.png',
                'name' => 'Digital Marketing',
                'slug' => Str::slug('Digital Marketing'),
                'parent_id' => null,
                'show_at_trending' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/categories_image/media_69495ba2bdc52.png',
                'name' => 'Graphic Design',
                'slug' => Str::slug('Graphic Design'),
                'parent_id' => null,
                'show_at_trending' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/categories_image/media_69495c7a85448.png',
                'name' => 'SEO Marketing',
                'slug' => Str::slug('SEO Marketing'),
                'parent_id' => null,
                'show_at_trending' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_69495ce1d8784.png',
                'name' => 'PHP',
                'slug' => Str::slug('PHP'),
                'parent_id' => 2,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_69495d3258ed2.png',
                'name' => 'Python',
                'slug' => Str::slug('Python'),
                'parent_id' => 2,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_69495d6f05aa1.png',
                'name' => 'C',
                'slug' => Str::slug('C'),
                'parent_id' => 2,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_69495df05f7f7.png',
                'name' => 'Go',
                'slug' => Str::slug('Go'),
                'parent_id' => 2,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_69496406ce5af.png',
                'name' => 'Facebook Marketing',
                'slug' => Str::slug('Facebook Marketing'),
                'parent_id' => 3,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_6949647b183f9.png',
                'name' => 'Youtube Marketing',
                'slug' => Str::slug('Youtube Marketing'),
                'parent_id' => 3,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_694964cc18fbb.png',
                'name' => 'Instagram Marketing',
                'slug' => Str::slug('Instagram Marketing'),
                'parent_id' => 3,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_6949653fd4708.png',
                'name' => 'Adobe Photoshop',
                'slug' => Str::slug('Adobe Photoshop'),
                'parent_id' => 4,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_69496584c1908.png',
                'name' => 'Adobe Illustrator',
                'slug' => Str::slug('Adobe Illustrator'),
                'parent_id' => 4,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_694965c4bcee1.png',
                'name' => 'Adobe XD',
                'slug' => Str::slug('Adobe XD'),
                'parent_id' => 4,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_6949662695443.png',
                'name' => 'Google',
                'slug' => Str::slug('Google'),
                'parent_id' => 5,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_6949666e2f48c.png',
                'name' => 'Youtube',
                'slug' => Str::slug('Youtube'),
                'parent_id' => 5,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_694966cb65257.png',
                'name' => 'HTML',
                'slug' => Str::slug('HTML'),
                'parent_id' => 1,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_6949670f36627.png',
                'name' => 'CSS',
                'slug' => Str::slug('CSS'),
                'parent_id' => 1,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'image' => 'uploads/seeder_image/sub_categories_image/media_694967581dca7.png',
                'name' => 'React JS',
                'slug' => Str::slug('React JS'),
                'parent_id' => 1,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
